# Generated by Django 6.0.4 on 2026-04-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoo',
            old_name='srno',
            new_name='id_todo',
        ),
    ]
